### ISSUE TITLE
Need Help Deleting /dfbdoom Directory.

### ISSUE THREAD

**Issue by JordanEJ** [fpv-wtf/dfbdoom#2]
When I used this command "adb push dfbdoom /blackbox" I accidently pushed the source code folder instead of the dfbdoom file. 

At the moment I can't overwrite it and i have tried to remove it with "rmdir" but without much success. Any help would be wonderful. I am afraid that if I mess around too much I might accidently mess other files up.

**Comment by jaanuke** [comment]
adb shell rm -r /blackbox/dfbdoom

**Comment by JordanEJ** [comment]
@jaanuke Thanks so much. I thought I tried that but I mustn't have. 😂
